---
name: alist-tvbox
slug: alist-tvbox
version: 521.1921
image: ghcr.io/solarflows/xiaoya-tvbox
description: "AList proxy server for TvBox, support playlist and search."
url: https://github.com/solarflows/HomeAssistant-Addons
init: false
codenotary: fireflows@cock.li
arch:
  - aarch64
  - amd64
map:
  - config:rw
  - ssl:ro
panel_icon: mdi:television-box
webui: "[PROTO:http]://[HOST]:[PORT:4567]"
privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH
ports:
  4567/tcp: 4567
  80/tcp: 5344
ports_description:
  4567/tcp: 'Manager Web UI port'
  80/tcp: 'Alist Web UI port'
startup: application
boot: manual
