name: 'Release Alist-tvbox Image To GHCR'

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/Release_Alist_tvbox.yml'
      - '.github/docker/alist-tvbox/*'
      - 'alist-tvbox/config.yaml'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry (ghcr)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.HASS_TOKEN }}

      - name: Set app version
        run: |
          # 读取本地版本（去除首尾空白/换行符）
          version=$(yq eval '.version' alist-tvbox/config.yaml | tr -d "'\n\r ")
          echo "APP_VERSION=$version" >> $GITHUB_ENV

      - name: Build Docker and push to ghcr
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: .github/docker/alist-tvbox/Dockerfile-xiaoya
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/xiaoya-tvbox:latest,ghcr.io/${{ github.repository_owner }}/xiaoya-tvbox:${{ env.APP_VERSION}}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # - name: Build host mode Docker and push to ghcr
      #   uses: docker/build-push-action@v5.3.0
      #   with:
      #     context: .
      #     file: .github/docker/alist-tvbox/Dockerfile-host
      #     platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: ghcr.io/${{ github.repository_owner }}/xiaoya-tvbox:hostmode,ghcr.io/${{ github.repository_owner }}/xiaoya-tvbox:hostmode-${{ env.APP_VERSION}}
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max

      - name: Build standalone Docker and push to ghcr
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: .github/docker/alist-tvbox/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/alist-tvbox:latest,ghcr.io/${{ github.repository_owner }}/alist-tvbox:${{ env.APP_VERSION}}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # - name: Build native Docker and push to ghcr
      #   uses: docker/build-push-action@v5.3.0
      #   with:
      #     context: .
      #     file: .github/docker/alist-tvbox/Dockerfile-native
      #     platforms: linux/amd64
      #     push: true
      #     tags: ghcr.io/${{ github.repository_owner }}/xiaoya-tvbox:native,ghcr.io/${{ github.repository_owner }}/xiaoya-tvbox:native-${{ env.APP_VERSION}}
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max

      # - name: Build host native Docker and push to ghcr
      #   uses: docker/build-push-action@v5.3.0
      #   with:
      #     context: .
      #     file: .github/docker/alist-tvbox/Dockerfile-native-host
      #     platforms: linux/amd64
      #     push: true
      #     tags: ghcr.io/${{ github.repository_owner }}/xiaoya-tvbox:native-host,ghcr.io/${{ github.repository_owner }}/xiaoya-tvbox:native-host-${{ env.APP_VERSION}}
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max
